default:
  image: docker-proxy.artifactory.ikarem.io/node:14-stretch
  before_script:
    - cat $SECRET_NPMRC >> .npmrc
    - npm ci --cache .npm --prefer-offline
    - npm install

stages:
  - setup
  - build
  - lint
  - test
  - publish

setup:
  stage: setup
  script:
    - echo "Seting up project..."
  artifacts:
    paths:
      - .npm

build:
  stage: build
  needs:
    - setup
  script:
    - echo "Building package..."
    - npm run build

lint:
  stage: lint
  needs:
    - setup
  script:
    - echo "Linting code..."
    - npm run lint

test:
  stage: test
  needs:
    - setup
  script:
    - echo "Running unit tests..."
    - npm run test

publish:
  stage: publish
  when: manual
  needs:
    - build
  script:
    - echo "Publishing package to Artifactory..."
    - npm run publish
